### ISSUE TITLE
Screen doesn't reset after pressing escape

### ISSUE THREAD

**Issue by snippins** [roy2220/easyjump.tmux#3]
After typing 2 chars and the hints appears, if I press escape to try getting out of easyjump, the screen isn't reset at all and the hints stay.

**Comment by roy2220** [comment]
Since easyjump.tmux interacts with users via the `command-prompt` function of Tmux, unfortunately, we can not get the notification of the cancellation of `command-prompt` now, just because Tmux does not provide the ability to achieve this.

But here is a workaround, you can press <kbd>Enter</kbd> to exit from easyjump.tmux.

**Comment by snippins** [comment]
@roy2220 Thanks for the workaround, so that why with tmux-jump they have somekind of seperate mode, and I need escape 2 times to get out.

You might want to add the workaround into README, as I think most people would try to use escape and think this is broken.

**Comment by roy2220** [comment]
> @roy2220 Thanks for the workaround, so that why with tmux-jump they have somekind of seperate mode, and I need escape 2 times to get out.
> 
> You might want to add the workaround into README, as I think most people would try to use escape and think this is broken.

Good point. I will make it notable in README.
