### ISSUE TITLE
[Bug Report] Pane color is not reset after cancel calling easyjump

### ISSUE THREAD

**Issue by laggardkernel** [roy2220/easyjump.tmux#6]
How to reproduce: trigger easymotion, type 2 chars, and press <kbd>ESC</kbd> to cancel.

Seem we failed to exit running easymotion. Color in the pane is not reset.

Update: it resets the pane color after about half a minute.

**Comment by roy2220** [comment]
Hi @laggardkernel , you can use <kbd>Enter</kbd> instead of <kbd>ESC</kbd> to cancel. This plugin depends on the functionality of Tmux's prompt, however, we can't get the notification of the quit from Tmux's prompt, simply Tmux don't provide the ability.  <kbd>Enter</kbd> is exactly the workaround for this issue.

**Comment by laggardkernel** [comment]
Thanks for your explanation.
